kind: pipeline
name: default

steps:
- name: getting_started
  image: golang:1.14.3
  commands:
  - go version

- name: your_first_program
  image: golang:1.14.3
  commands:
  - go run 02_your_first_program/main.go
  - go run 02_your_first_program/name.go

- name: types
  image: golang:1.14.3
  commands:
  - go run 03_types/numbers.go
  - go run 03_types/strings.go
  - go run 03_types/booleans.go
  - go run 03_types/calc.go
  - go run 03_types/value.go

- name: variables
  image: golang:1.14.3
  commands:
  - go run 04_variables/hello.go
  - go run 04_variables/strings.go
  - go run 04_variables/name.go
  - go run 04_variables/scope.go
  - go run 04_variables/constants.go
  - go run 04_variables/multiples.go
  - go run 04_variables/example.go
  - go run 04_variables/value.go
  - go run 04_variables/temp.go
  - go run 04_variables/length.go

- name: control_structures
  image: golang:1.14.3
  commands:
  - go run 05_control_structures/for.go
  - go run 05_control_structures/if.go
  - go run 05_control_structures/switch.go
  - go run 05_control_structures/problem.go
  - go run 05_control_structures/divisable.go
  - go run 05_control_structures/fizzer.go
