kind: pipeline
name: default

steps:
- name: getting_started
  image: golang:1.14.3
  commands:
  - go version

- name: your_first_program
  image: golang:1.14.3
  commands:
  - go run 02_your_first_program/main.go
  - go run 02_your_first_program/name.go

- name: types
  image: golang:1.14.3
  commands:
  - go run 03_types/numbers.go
  - go run 03_types/strings.go
  - go run 03_types/booleans.go
  - go run 03_types/calc.go
  - go run 03_types/value.go
