kind: pipeline
name: default

steps:
- name: getting_started
  image: golang:1.14.3
  commands:
  - go version

- name: your_first_program
  image: golang:1.14.3
  commands:
  - go run 02_your_first_program/main.go
  - go run 02_your_first_program/name.go

- name: types
  image: golang:1.14.3
  commands:
  - go run 03_types/numbers.go
  - go run 03_types/strings.go
  - go run 03_types/booleans.go
  - go run 03_types/calc.go
  - go run 03_types/value.go

- name: variables
  image: golang:1.14.3
  commands:
  - go run 04_variables/hello.go
  - go run 04_variables/strings.go
  - go run 04_variables/name.go
  - go run 04_variables/scope.go
  - go run 04_variables/constants.go
  - go run 04_variables/multiples.go
  - go run 04_variables/example.go
  - go run 04_variables/value.go
  - go run 04_variables/temp.go
  - go run 04_variables/length.go

- name: control_structures
  image: golang:1.14.3
  commands:
  - go run 05_control_structures/for.go
  - go run 05_control_structures/if.go
  - go run 05_control_structures/switch.go
  - go run 05_control_structures/problem.go
  - go run 05_control_structures/divisable.go
  - go run 05_control_structures/fizzer.go

- name: arrays_slices_maps
  image: golang:1.14.3
  commands:
  - go run 06_arrays_slices_maps/arrays.go
  - go run 06_arrays_slices_maps/slices.go
  - go run 06_arrays_slices_maps/maps.go
  - go run 06_arrays_slices_maps/fourth.go
  - go run 06_arrays_slices_maps/length.go
  - go run 06_arrays_slices_maps/two_to_five.go
  - go run 06_arrays_slices_maps/smallest.go

- name: functions
  image: golang:1.14.3
  commands:
  - go run 07_functions/second.go
  - go run 07_functions/multiples.go
  - go run 07_functions/variadic.go
  - go run 07_functions/closure.go
  - go run 07_functions/recursion.go
  - go run 07_functions/defer.go
  - go run 07_functions/panic_recover.go
  - go run 07_functions/sum.go
  - go run 07_functions/true_or_false.go
  - go run 07_functions/greatest.go
  - go run 07_functions/make_odd.go
  - go run 07_functions/fib.go

- name: pointers
  image: golang:1.14.3
  commands:
  - go run 08_pointers/zero.go
  - go run 08_pointers/new.go
  - go run 08_pointers/value.go
  - go run 08_pointers/swapper.go

- name: structs_and_interfaces
  image: golang:1.14.3
  commands:
  - go run 09_structs_and_interfaces/shapes.go
  - go run 09_structs_and_interfaces/embedded.go

- name: concurrency
  image: golang:1.14.3
  commands:
  - go run 10_concurrency/goroutines.go
  - go run 10_concurrency/channels.go
  - go run 10_concurrency/select.go
  - go run 10_concurrency/sleeper.go

- name: packages
  image: golang:1.14.3
  commands:
  - go run 11_packages/main.go
